Mengimpor package yang diperlukan

In [10]:
import numpy as np 
import pandas as pd 
from sklearn.metrics import confusion_matrix 
from sklearn.tree import DecisionTreeClassifier 
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 
import matplotlib.pyplot as plt 

Fungsi untuk mengimpor dataset

In [11]:
def importdata(): 
    dataset = pd.read_csv(r"C:\Users\Shella Lolitha\Documents\Python Jupyter\datamhs_clean2.csv")
    dataset2 = dataset[['kdjur', 'kdsla', 'nem', 'sks', 'ipk']]
    dataset2 = dataset2._get_numeric_data()
      
    # Printing the dataswet shape 
    print ("Dataset Lenght: ", len(dataset2)) 
    print ("Dataset Shape: ", dataset2.shape) 
      
    # Printing the dataset obseravtions 
    print ("Dataset: ",dataset2.head()) 
    return dataset2 

Fungsi untuk melakukan split pada dataset

In [12]:
def splitdataset(dataset2): 
  
    # Seperating the target variable 
    X = dataset2[['kdjur', 'nem', 'sks']].astype(int) 
    Y = dataset2[['ipk']].astype(int) 
  
    # Spliting the dataset into train and test 
    X_train, X_test, y_train, y_test = train_test_split(  
    X, Y, test_size = 0.3, random_state = 100) 
      
    return X, Y, X_train, X_test, y_train, y_test 

Fungsi untuk melakukan training menggunakan giniIndex

In [13]:
def train_using_gini(X_train, X_test, y_train): 
  
    # Creating the classifier object 
    clf_gini = DecisionTreeClassifier(criterion = "gini", 
            random_state = 100,max_depth=3, min_samples_leaf=5) 
  
    # Performing training 
    clf_gini.fit(X_train, y_train) 
    return clf_gini 

Fungsi untuk melakukan data training dengan entropy.

In [14]:
def tarin_using_entropy(X_train, X_test, y_train): 
  
    # Decision tree with entropy 
    clf_entropy = DecisionTreeClassifier( 
            criterion = "entropy", random_state = 100, 
            max_depth = 3, min_samples_leaf = 5) 
  
    # Performing training 
    clf_entropy.fit(X_train, y_train) 
    return clf_entropy 

Fungsi untuk membuat prediksi

In [15]:
def prediction(X_test, clf_object): 
  
    # Predicton on test with giniIndex 
    y_pred = clf_object.predict(X_test) 
    print("Predicted values:") 
    print(y_pred) 
    return y_pred 

Fungsi untuk mengkalkulasi akurasi

In [16]:
def cal_accuracy(y_test, y_pred): 
      
    print("Confusion Matrix: ", 
        confusion_matrix(y_test, y_pred)) 
      
    print ("Accuracy : ", 
    accuracy_score(y_test,y_pred)*100) 
      
    print("Report : ", 
    classification_report(y_test, y_pred)) 

Fungsi main

In [17]:
def main(): 
      
    # Building Phase 
    data = importdata() 
    X, Y, X_train, X_test, y_train, y_test = splitdataset(data) 
    
    clf_gini = train_using_gini(X_train, X_test, y_train) 
    clf_entropy = tarin_using_entropy(X_train, X_test, y_train) 
      
    # Operational Phase 
    print("Results Using Gini Index:") 
      
    # Prediction using gini 
    y_pred_gini = prediction(X_test, clf_gini) 
    cal_accuracy(y_test, y_pred_gini) 
      
    print("Results Using Entropy:") 
    # Prediction using entropy 
    y_pred_entropy = prediction(X_test, clf_entropy) 
    cal_accuracy(y_test, y_pred_entropy) 


Memanggil fungsi main

In [18]:
if __name__=="__main__": 
    main() 

Dataset Lenght:  16053
Dataset Shape:  (16053, 4)
Dataset:     kdjur    nem  sks   ipk
0     71  40.70  2.0  3.19
1     71  48.95  2.0  3.30
2     71  49.00  2.0  3.23
3     71  49.75  2.0  3.40
4     71  44.35  3.0  3.30
Results Using Gini Index:
Predicted values:
[3 2 3 ... 3 3 2]
Confusion Matrix:  [[   0    0    0    3]
 [   0    0   12   36]
 [   0    0  283 1140]
 [   0    0  113 3229]]
Accuracy :  72.9235880398671
Report :                precision    recall  f1-score   support

           0       0.00      0.00      0.00         3
           1       0.00      0.00      0.00        48
           2       0.69      0.20      0.31      1423
           3       0.73      0.97      0.83      3342

   micro avg       0.73      0.73      0.73      4816
   macro avg       0.36      0.29      0.29      4816
weighted avg       0.71      0.73      0.67      4816

Results Using Entropy:
Predicted values:
[3 2 3 ... 3 3 2]
Confusion Matrix:  [[   0    0    0    3]
 [   0    0    8   40]
 [   0

C:\Users\Shella Lolitha\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Shella Lolitha\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
